language: python
python:
  - "2.7"
services:
  - postgresql
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq libpq-dev 
#   - sudo apt-get install postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE USER django;' -U postgres
  - psql -c 'ALTER USER django CREATEDB;' -U postgres
script:
  - python manage.py test
# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
#script: nosetests

deploy:
  provider: codedeploy
  access_key_id: "AKIAISCPLKYOXYQHEAWA"
  secret_access_key: "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"
  bucket: "S3 Bucket"
  key: latest/learn_django.zip
  application: learn_django
  deployment_group: MyDeploymentGroup