language: python
python:
  - "3.4"
env:
  - DJANGO=1.8
install:
  -	pip install -q Django==$DJANGO 
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script:
  - python setup.py test
# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
#script: nosetests

deploy:
  provider: codedeploy
  access_key_id: "AKIAISCPLKYOXYQHEAWA"
  secret_access_key: "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"
  bucket: "S3 Bucket"
  key: latest/learn_django.zip
  application: learn_django
  deployment_group: MyDeploymentGroup