language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
sudo: required
install:
  - "pip install ."
script:
  - python blog/tests.py

# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
#script: nosetests

deploy:
  provider: codedeploy
  access_key_id: "AKIAISCPLKYOXYQHEAWA"
  secret_access_key: "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"
  bucket: "S3 Bucket"
  key: latest/learn_django.zip
  application: learn_django
  deployment_group: MyDeploymentGroup